server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.214.89:3306/yeb?useUnicode=true
    username: root
    password: 314159AK-47
    hikari:
      # 连接池名
      pool-name: DateHikaricp
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接存活最大连接时间，默认600000（10分钟）
      idle-timeout: 180000
      #最大连接数，默认110
      maximum-pool-size: 10
      #从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间。默认30000（30s）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # Redis配置
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: 8.131.61.35                   # Redis服务器地址
    password: 314159
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5                          # 最小空闲连接，默认 0
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 212.129.238.55
    # 端口
    port: 5672
    # 消息失败回调
    publisher-returns: true
    # 消息确认回调
    publisher-confirm-type: correlated

# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
#  配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.hyf.server.pojo
  configuration:
    map-underscore-to-camel-case: false

#  Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)


jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer


