server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: IOWQSQNVULNYPWKU
    # 发送者邮箱地址
    username: yzyzhongyunfeng@163.com
    # 端口（不同邮箱端口号不同）
    port: 25
  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 212.129.238.55
    # 端口
    port: 5672
    listener:
      simple:
        # 手动确认
        acknowledge-mode: manual
  # redis配置
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: 8.131.61.35                   # Redis服务器地址
    password: 314159
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5
  main:
    allow-bean-definition-overriding: true
